'use strict';
const LIB=window.PAPER_LIBRARY;
const CARDS=LIB.cards;
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const PATHS={arrow:'M5 12h14m-5-5 5 5-5 5',search:'m20 20-4.5-4.5M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0',grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',list:'M8 5h13M8 12h13M8 19h13M3 5h.01M3 12h.01M3 19h.01',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',bookmark:'M6 3h12v18l-6-4-6 4V3Z',compare:'M4 4h6v16H4zM14 4h6v16h-6z',close:'m6 6 12 12M18 6 6 18',expand:'M9 3H3v6m12-6h6v6M3 15v6h6m12-6v6h-6',cube:'m12 3 9 5v9l-9 5-9-5V8l9-5Zm0 10 9-5M3 8l9 5v9M7.5 5.5l9 5',filter:'M4 6h16M7 12h10m-7 6h4',spark:'m12 2 2.5 7.5L22 12l-7.5 2.5L12 22l-2.5-7.5L2 12l7.5-2.5L12 2Z',check:'m5 12 4 4L19 6',note:'M4 3h16v18H4zM8 8h8M8 12h8M8 16h5'};
function icon(name){return `<span class="icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="${PATHS[name]||PATHS.note}"/></svg></span>`}
function fillIcons(root=document){root.querySelectorAll('[data-icon]').forEach(e=>{e.innerHTML=`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${PATHS[e.dataset.icon]||PATHS.note}"/></svg>`})}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function safeURL(url){try{const u=new URL(url,location.href);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}}
function link(url,text,cls=''){const good=safeURL(url);return good?`<a href="${esc(good)}" target="_blank" rel="noopener noreferrer" class="${cls}">${esc(text)} ↗</a>`:''}
const byId=id=>CARDS.find(c=>c.id===id),bySlug=slug=>CARDS.find(c=>c.slug===slug),domainsOf=c=>Array.isArray(c.domainGroups)&&c.domainGroups.length?c.domainGroups:[c.domainGroup||OTHER];
const TAXONOMY=LIB.taxonomy||{};
const OTHER=TAXONOMY.otherLabel||'其他';
const DOMAIN_GROUPS=Object.keys(TAXONOMY.domainGroups||{});
const METHOD_FAMILIES=TAXONOMY.methodFamilies||[...new Set(CARDS.map(c=>c.methodFamily||OTHER))];
const PROBLEM_TYPES=TAXONOMY.problemTypes||[...new Set(CARDS.map(c=>c.problemType||OTHER))];
const LABORATORIES=Object.keys(TAXONOMY.laboratories||{});
const GROUP_COLORS=['#00468B','#1479A8','#1B8A89','#2F6FC2','#7954A8','#B06A24','#C45E32','#9B4677','#40816C','#6B7F3A'];
const STORE='paper-atlas.collection.v1';
const PAGE_SIZE=36;
let persisted={};try{persisted=JSON.parse(localStorage.getItem(STORE)||'{}')}catch{}
if(!persisted||typeof persisted!=='object')persisted={};
const state={page:'explore',layout:'grid',q:'',domainGroup:'',domain:'',methodFamily:'',problemType:'',laboratory:'',dataSubtype:'',year:'',sort:'curated',visible:PAGE_SIZE,mapPage:0,saved:new Set((Array.isArray(persisted.saved)?persisted.saved:[]).filter(byId)),notes:typeof persisted.notes==='object'&&persisted.notes?persisted.notes:{},compare:[],reader:null,readerTab:'overview'};
let lastFocus=null,toastTimer=null;
function persist(){try{localStorage.setItem(STORE,JSON.stringify({saved:[...state.saved],notes:state.notes}));return true}catch{return false}}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2700)}
function filtered(){const terms=state.q.toLocaleLowerCase().trim().split(/\s+/).filter(Boolean);let arr=CARDS.filter(c=>(state.page!=='saved'||state.saved.has(c.id))&&(!state.domainGroup||domainsOf(c).includes(state.domainGroup))&&(!state.domain||c.major===state.domain)&&(!state.methodFamily||c.methodFamily===state.methodFamily)&&(!state.problemType||c.problemType===state.problemType)&&(!state.laboratory||c.laboratory===state.laboratory)&&(!state.dataSubtype||c.dataSubtype===state.dataSubtype)&&(!state.year||String(c.year)===state.year)&&terms.every(t=>[c.title,c.short,c.originalTitle,c.major,domainsOf(c).join(' '),c.method,c.methods.join(' '),c.methodFamily,c.problemType,c.laboratory,c.dataSubtype,c.creativeForm,c.question,c.aiMethod,c.data,c.dataType,c.doi,c.markdown].join(' ').toLocaleLowerCase().includes(t)));if(state.sort==='newest')arr.sort((a,b)=>b.year-a.year);if(state.sort==='oldest')arr.sort((a,b)=>a.year-b.year);if(state.sort==='domain')arr.sort((a,b)=>cjk(domainsOf(a)[0],domainsOf(b)[0])||cjk(a.major,b.major));return arr}
function cjk(a,b){return String(a||'').localeCompare(String(b||''),'zh-CN')}
function filterButton(key,value,label,n,kind='method-filter',color=''){const active=state[key]===value;return `<button class="${kind} ${active?'active':''}" data-filter-key="${key}" data-filter-value="${esc(value)}" aria-pressed="${active}"${color?` style="--dot:${color}"`:''}>${kind==='domain-filter'?'<span class="domain-dot"></span>':''}<span>${esc(label)}</span><span class="n">${n}</span></button>`}
function renderFilters(){const base=state.page==='saved'?CARDS.filter(c=>state.saved.has(c.id)):CARDS;const domainGroups=[...DOMAIN_GROUPS,OTHER].filter(g=>base.some(c=>domainsOf(c).includes(g)));$('#domain-filters').innerHTML=filterButton('domainGroup','','全部领域',base.length,'domain-filter','#718ea4')+domainGroups.map((g,i)=>filterButton('domainGroup',g,g,base.filter(c=>domainsOf(c).includes(g)).length,'domain-filter',GROUP_COLORS[i%GROUP_COLORS.length])).join('');const domains=state.domainGroup?(TAXONOMY.domainGroups?.[state.domainGroup]||[...new Set(base.filter(c=>domainsOf(c).includes(state.domainGroup)).map(c=>c.major))]):[];$('#domain-detail-wrap').hidden=!domains.length;$('#domain-detail-filters').innerHTML=domains.filter(d=>base.some(c=>c.major===d)).map(d=>filterButton('domain',d,d,base.filter(c=>c.major===d).length,'major-filter')).join('');$('#method-filters').innerHTML=METHOD_FAMILIES.filter(m=>base.some(c=>c.methodFamily===m)).map(m=>filterButton('methodFamily',m,m,base.filter(c=>c.methodFamily===m).length)).join('');$('#problem-filters').innerHTML=PROBLEM_TYPES.filter(p=>base.some(c=>c.problemType===p)).map(p=>filterButton('problemType',p,p,base.filter(c=>c.problemType===p).length)).join('');const laboratories=[...LABORATORIES,OTHER].filter(l=>base.some(c=>c.laboratory===l));$('#lab-filters').innerHTML=laboratories.map((l,i)=>{const subtypes=(TAXONOMY.laboratories?.[l]||[...new Set(base.filter(c=>c.laboratory===l).map(c=>c.dataSubtype))]).filter(s=>base.some(c=>c.laboratory===l&&c.dataSubtype===s));return`<div class="lab-filter-group">${filterButton('laboratory',l,l,base.filter(c=>c.laboratory===l).length,'domain-filter',GROUP_COLORS[(i+2)%GROUP_COLORS.length])}<div class="lab-data-types">${subtypes.map(s=>`<button class="data-type-filter ${state.dataSubtype===s?'active':''}" data-filter-key="dataSubtype" data-filter-value="${esc(s)}" data-lab="${esc(l)}" aria-pressed="${state.dataSubtype===s}"><span>${esc(s)}</span><span class="n">${base.filter(c=>c.laboratory===l&&c.dataSubtype===s).length}</span></button>`).join('')}</div></div>`}).join('');const years=[...new Set(CARDS.map(c=>c.year))].sort(),max=Math.max(1,...years.map(y=>base.filter(c=>c.year===y).length));$('#year-filters').innerHTML=years.map(y=>{const n=base.filter(c=>c.year===y).length;return`<button class="year-filter ${state.year===String(y)?'active':''}" data-filter-key="year" data-filter-value="${y}" aria-pressed="${state.year===String(y)}"><span>${y}</span><span class="year-bar" style="--width:${n/max*100}%"><i></i></span><span>${n}</span></button>`}).join('');const active=['domainGroup','domain','methodFamily','problemType','laboratory','dataSubtype','year'].map(key=>[key,state[key]]).filter(([,value])=>value);$('#active-filters').innerHTML=active.map(([key,value])=>`<button data-clear="${key}" aria-label="取消${esc(value)}筛选">${esc(value)} <span>×</span></button>`).join('');$('#filter-mobile-count').textContent=active.length?`${active.length} 个筛选条件`:'全部论文'}
function cardMarkup(c){const saved=state.saved.has(c.id),compared=state.compare.includes(c.id);return `<article class="paper-card" data-id="${c.id}" style="--color:${c.color};--tone:${c.tone}"><div class="paper-tools"><button class="small-tool ${saved?'on':''}" data-save="${c.id}" aria-label="${saved?'取消收藏':'收藏'}：${esc(c.short)}" aria-pressed="${saved}" title="${saved?'取消收藏':'收藏论文'}">${icon('bookmark')}</button><button class="small-tool ${compared?'on':''}" data-compare="${c.id}" aria-label="${compared?'移出比较':'加入比较'}：${esc(c.short)}" aria-pressed="${compared}" title="${compared?'移出比较':'加入比较'}">${icon('compare')}</button></div><a class="paper-cover" href="#paper/${c.slug}" aria-label="阅读：${esc(c.title)}"><img src="${c.image}" alt="${esc(c.major)}论文原始卡片" loading="lazy" decoding="async" width="1086" height="1448">${c.interactive?`<span class="interactive-pill">${icon('cube')}含交互实验</span>`:''}</a><div class="paper-body"><div class="paper-meta"><span class="paper-domain">${esc(c.major)}</span><span class="paper-year">${c.year}</span></div><h3 class="paper-title"><a href="#paper/${c.slug}">${esc(c.short)}</a></h3><p class="paper-summary">${esc(c.summary)}</p>${c.creativeForm?`<p class="paper-form">${esc(c.creativeForm)}</p>`:''}<div class="paper-taxonomy"><button data-filter-key="laboratory" data-filter-value="${esc(c.laboratory)}">${esc(c.laboratory)}</button><button data-filter-key="methodFamily" data-filter-value="${esc(c.methodFamily)}">${esc(c.methodFamily)}</button><button data-filter-key="problemType" data-filter-value="${esc(c.problemType)}">${esc(c.problemType)}</button></div><div class="paper-journal">${esc(c.venue)}</div><div class="paper-foot"><button data-filter-key="dataSubtype" data-filter-value="${esc(c.dataSubtype)}" data-lab="${esc(c.laboratory)}">数据类型 · ${esc(c.dataSubtype)}</button><a href="#paper/${c.slug}" aria-label="阅读完整卡片：${esc(c.title)}">阅读全文 ${icon('arrow')}</a></div></div></article>`}
function recoverImages(){$$('.paper-cover img').forEach(img=>img.addEventListener('error',()=>{if(img.dataset.retried)return;img.dataset.retried='true';const src=img.getAttribute('src');setTimeout(()=>{img.src=src+(src.includes('?')?'&':'?')+'retry='+Date.now()},250)},{once:true}))}
function render(){document.body.dataset.page=state.page;$$('[data-page]').forEach(a=>{a.classList.toggle('active',a.dataset.page===state.page);a.setAttribute('aria-current',a.dataset.page===state.page?'page':'false')});$('#saved-count').textContent=state.saved.size;const names={explore:['THE COLLECTION','一张卡片，一个研究入口','来自你的真实论文卡片库'],map:['CONNECTED IDEAS','沿着方法，发现跨学科的连接','按卡片内容整理的方法分类'],saved:['YOUR READING SHELF','留给下一次灵感的论文','收藏与笔记，保存在当前浏览器']};const name=names[state.page];$('#section-eyebrow').textContent=name[0];$('#collection-title').innerHTML=`${name[1]}<span class="count-badge" id="result-count"></span>`;$('#collection-note').textContent=name[2];const arr=filtered(),visible=arr.slice(0,state.visible);$('#result-count').textContent=arr.length;$('#result-announcement').textContent=`共 ${arr.length} 篇论文，当前载入 ${visible.length} 篇`;renderFilters();$('#paper-grid').className='paper-grid'+(state.layout==='list'?' list':'');$('#paper-grid').innerHTML=visible.map(cardMarkup).join('');recoverImages();$('#paper-grid').hidden=state.page==='map'||!arr.length;$('#map-view').hidden=state.page!=='map'||!arr.length;$('#empty-state').hidden=!!arr.length;const footer=$('#results-footer');footer.hidden=!arr.length||state.page==='map';footer.innerHTML=visible.length<arr.length?`<span>已显示 ${visible.length} / ${arr.length} 篇</span><button id="load-more" class="load-more">继续加载 ${Math.min(PAGE_SIZE,arr.length-visible.length)} 篇</button>`:`<span>已显示全部 ${arr.length} 篇。</span><span>每篇论文均保留完整正文与原始卡片。</span>`;$('#view-grid').classList.toggle('active',state.layout==='grid');$('#view-list').classList.toggle('active',state.layout==='list');$('#view-grid').setAttribute('aria-pressed',String(state.layout==='grid'));$('#view-list').setAttribute('aria-pressed',String(state.layout==='list'));if(!arr.length){const noSaved=state.page==='saved'&&!state.saved.size;$('#empty-state').innerHTML=`${icon(noSaved?'bookmark':'search')}<h3>${noSaved?'给下一次灵感，留一个位置。':'还没有找到匹配的论文'}</h3><p>${noSaved?'在卡片右上角点一下书签，喜欢的论文就会出现在这里。':'试试更短的关键词，或调整学科、方法与年份。'}</p><button class="button primary" id="empty-action">${noSaved?'去探索论文':'清除筛选'}</button>`}if(state.page==='map'&&arr.length)renderMap(arr);renderCompareBar();if(state.reader)updateReaderActions()}
function clearFilters(){for(const key of ['domainGroup','domain','methodFamily','problemType','laboratory','dataSubtype','year'])state[key]='';state.q='';state.visible=PAGE_SIZE;state.mapPage=0;$('#search').value='';render()}
function setPage(page){if(!['explore','map','saved'].includes(page))page='explore';const changed=state.page!==page;state.page=page;if(changed)state.visible=PAGE_SIZE;render();if(changed)window.scrollTo({top:0,behavior:'instant'})}
function toggleSave(id){if(!byId(id))return;const remove=state.saved.has(id);if(remove)state.saved.delete(id);else state.saved.add(id);const stored=persist();render();toast(stored?(remove?'已从收藏中移除':'已加入我的收藏'):'本次已收藏；浏览器未允许长期保存')}
function toggleCompare(id){if(!byId(id))return;if(state.compare.includes(id))state.compare=state.compare.filter(x=>x!==id);else{if(state.compare.length>=3){toast('最多同时比较 3 篇论文，请先移出一篇。');return}state.compare.push(id)}render();if(state.compare.length===1)toast('再选择一篇论文，就可以开始比较。')}
function renderCompareBar(){$('#compare-bar').hidden=!state.compare.length;$('#compare-count').textContent=`${state.compare.length} / 3`;$('#compare-chips').innerHTML=state.compare.map(id=>{const c=byId(id);return`<span class="compare-chip"><span>${esc(c.major)}</span><button data-compare="${id}" aria-label="移出比较：${esc(c.short)}">×</button></span>`}).join('');$('#open-compare').disabled=state.compare.length<2;$('#open-compare').textContent=state.compare.length>1?'开始比较 ↗':'再选一篇'}
function download(text,name,type='text/markdown;charset=utf-8'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}

function inlineMD(raw){const tokens=[];const put=h=>{const key=`ZZTOKEN${tokens.length}ZZ`;tokens.push(h);return key};let s=raw.replace(/`([^`]+)`/g,(_,v)=>put(`<code>${esc(v)}</code>`));s=s.replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,(_,label,url)=>put(link(url,label)));s=s.replace(/https?:\/\/[^\s<>]+/g,url=>{const trimmed=url.replace(/[。；，]+$/,'');return put(link(trimmed,trimmed))+esc(url.slice(trimmed.length))});s=esc(s).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>');return s.replace(/ZZTOKEN(\d+)ZZ/g,(_,i)=>tokens[+i])}
function markdownHTML(md){const lines=md.replace(/\r/g,'').split('\n');let html='',i=0;const cells=l=>l.trim().replace(/^\||\|$/g,'').split('|').map(x=>x.trim());while(i<lines.length){let line=lines[i];if(!line.trim()){i++;continue}if(/^```/.test(line)){const code=[];i++;while(i<lines.length&&!/^```/.test(lines[i]))code.push(lines[i++]);i++;html+='<pre><code>'+esc(code.join('\n'))+'</code></pre>';continue}if(/^\s*\|/.test(line)&&i+1<lines.length&&/^\s*\|?\s*:?-{2,}/.test(lines[i+1])){const head=cells(line);i+=2;let rows='';while(i<lines.length&&/^\s*\|/.test(lines[i]))rows+='<tr>'+cells(lines[i++]).map(c=>'<td>'+inlineMD(c)+'</td>').join('')+'</tr>';html+='<div class="md-table"><table><thead><tr>'+head.map(c=>'<th>'+inlineMD(c)+'</th>').join('')+'</tr></thead><tbody>'+rows+'</tbody></table></div>';continue}const heading=line.match(/^(#{1,6})\s+(.+)$/);if(heading){const level=Math.min(5,heading[1].length+2);html+=`<h${level}>${inlineMD(heading[2])}</h${level}>`;i++;continue}if(/^\s*[-*]\s+/.test(line)||/^\s*\d+\.\s+/.test(line)){const ordered=/^\s*\d+\./.test(line),tag=ordered?'ol':'ul',test=ordered?/^\s*\d+\.\s+/:/^\s*[-*]\s+/;let list='';while(i<lines.length&&test.test(lines[i]))list+='<li>'+inlineMD(lines[i++].replace(test,''))+'</li>';html+=`<${tag}>${list}</${tag}>`;continue}if(/^>\s?/.test(line)){html+='<blockquote>'+inlineMD(line.replace(/^>\s?/,''))+'</blockquote>';i++;continue}if(/^---+$/.test(line.trim())){html+='<hr>';i++;continue}const para=[line];i++;while(i<lines.length&&lines[i].trim()&&!/^(#{1,6}\s|[-*]\s|\d+\.\s|```|\||>)/.test(lines[i]))para.push(lines[i++]);html+='<p>'+para.map(inlineMD).join('<br>')+'</p>'}return html}
function updateReaderActions(){const c=state.reader;if(!c)return;const saved=state.saved.has(c.id),selected=state.compare.includes(c.id);$('#reader-save').innerHTML=icon(saved?'check':'bookmark')+(saved?'已收藏':'收藏论文');$('#reader-save').setAttribute('aria-pressed',String(saved));$('#reader-compare').innerHTML=icon('compare')+(selected?'已加入比较':'加入比较');$('#reader-compare').setAttribute('aria-pressed',String(selected));$('#note-dot').textContent=typeof state.notes[c.id]==='string'&&state.notes[c.id].trim()?'有笔记':''}
function overview(c){const dataLabel=/github|zenodo|figshare|osf\.io/.test(c.dataUrl)?'数据入口':'数据来源说明';return `${c.creativeForm?`<div class="question-box"><small>创意呈现</small>${esc(c.creativeForm)}</div>`:''}<div class="question-box"><small>从这个问题开始</small>${esc(c.question)}</div><section class="reading-section"><h3><span>01</span>数据从哪里来</h3><p>${esc(c.data)}</p><div class="classification-strip"><span>实验室 · ${esc(c.laboratory)}</span><span>数据类型 · ${esc(c.dataSubtype)}</span><span>${esc(c.problemType)}</span></div>${c.dataType||c.availability?`<div class="data-detail">${c.dataType?`<div><b>原卡数据描述</b>${esc(c.dataType)}</div>`:''}${c.availability?`<div><b>可用性记录</b>${esc(c.availability)}</div>`:''}</div>`:''}</section><section class="reading-section"><h3><span>02</span>AI 在研究中做什么</h3><p>${esc(c.aiMethod)}</p></section><section class="reading-section"><h3><span>03</span>研究怎样一步步完成</h3><div class="pipeline">${c.pipeline.map((s,i)=>`<div><span>${String(i+1).padStart(2,'0')}</span><strong>${esc(s.title)}</strong>${s.detail?`<small>${esc(s.detail)}</small>`:''}</div>`).join('')}</div></section><section class="reading-section"><h3><span>04</span>论文报告了什么</h3><div class="result-box"><p>${esc(c.result)}</p></div>${c.metrics?`<p class="validation-text">评价指标：${esc(c.metrics)}</p>`:''}${c.validation?`<p class="validation-text">验证记录：${esc(c.validation)}</p>`:''}${c.boundary?`<div class="boundary">${esc(c.boundary)}</div>`:''}</section><section class="reading-section"><h3><span>05</span>继续阅读与复现</h3><div class="resource-links">${link(c.sourceUrl,'原论文')}${c.dataUrl?link(c.dataUrl,dataLabel):''}${c.codeUrl?link(c.codeUrl,'代码入口'):''}</div>${!c.dataUrl||!c.codeUrl?`<div class="resource-missing">${!c.dataUrl?'独立数据入口：原卡未提供。 ':''}${!c.codeUrl?'独立代码入口：原卡未提供。':''}</div>`:''}</section>`}
function renderReaderTab(){const c=state.reader;if(!c)return;$$('[data-reader-tab]').forEach(b=>{const active=b.dataset.readerTab===state.readerTab;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1});$('#reader-panel').setAttribute('aria-labelledby','tab-'+state.readerTab);if(state.readerTab==='overview')$('#reader-panel').innerHTML=overview(c);if(state.readerTab==='full')$('#reader-panel').innerHTML='<div class="full-body">'+markdownHTML(c.markdown)+'</div>';if(state.readerTab==='notes'){const note=typeof state.notes[c.id]==='string'?state.notes[c.id]:'';$('#reader-panel').innerHTML=`<p class="notes-intro">把阅读时冒出的想法，留在这篇论文旁边。</p><label class="sr-only" for="paper-note">这篇论文的阅读笔记</label><textarea id="paper-note" class="note-field" maxlength="20000" placeholder="这个问题和我的课题有什么联系？\n哪些方法、数据或实验设计值得借鉴？\n下一步想验证什么？">${esc(note)}</textarea><div class="note-meta"><span id="note-save-state">${note?'已保存在当前浏览器':'输入后自动保存到当前浏览器'}</span><span id="note-length">${note.length} 字</span></div><div class="note-prompts"><b>可以从这三个问题开始</b>① 这篇研究解决了什么具体问题？<br>② 哪一步方法可以迁移到我的研究？<br>③ 我还需要什么数据或证据？</div>`;$('#paper-note').addEventListener('input',e=>{state.notes[c.id]=e.target.value;const ok=persist();$('#note-save-state').textContent=ok?'已保存到当前浏览器':'浏览器未允许保存，请复制备份';$('#note-length').textContent=e.target.value.length+' 字';updateReaderActions()})}}
function openReader(slug){const c=bySlug(slug);if(!c){location.hash=state.page;toast('没有找到这张卡片。');return}lastFocus=document.activeElement.closest('.paper-card,.graph-node')?document.activeElement:$('#search');state.reader=c;state.readerTab='overview';$('#reader-domain').textContent=c.major;$('#reader-domain').style.background=c.tone;$('#reader-domain').style.color=c.color;$('#reader-source').textContent=c.venue+' · '+c.year;$('#reader-image').src=c.image;$('#reader-image').alt=c.title+' · 原始论文卡片';$('#reader-kicker').textContent=c.laboratory+' · '+c.methodFamily;$('#reader-title').textContent=c.title;$('#reader-original').textContent=c.originalTitle;$('#reader-doi').href='https://doi.org/'+c.doi;$('#reader-doi').textContent='DOI  '+c.doi+'  ↗';$('#reader').setAttribute('aria-labelledby','reader-title');$('#reader-lab').hidden=!c.interactive;if(c.interactive)$('#reader-lab').href=c.interactive;updateReaderActions();renderReaderTab();if(!$('#reader').open)$('#reader').showModal();$('.reader-content').scrollTop=0;$('.reader-layout').scrollTop=0;$('#reader-close').focus({preventScroll:true})}
function closeReader(){location.hash=state.page}
function route(){const hash=decodeURIComponent(location.hash.slice(1)||'explore');if(hash.startsWith('paper/')){openReader(hash.slice(6));return}if($('#reader').open){$('#reader').close();state.reader=null;if(lastFocus&&lastFocus.isConnected)lastFocus.focus({preventScroll:true});else $('#search').focus({preventScroll:true})}if(hash==='collection'){if(state.page!=='explore'){setPage('explore')}requestAnimationFrame(()=>$('#collection').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'}));return}setPage(['explore','map','saved'].includes(hash)?hash:'explore')}
function openCompare(){if(state.compare.length<2)return;const cards=state.compare.map(byId);const fields=[['创意呈现',c=>c.creativeForm||'结构化论文卡'],['研究领域',c=>domainsOf(c).join(' · ')],['研究问题',c=>c.question],['数据基础',c=>c.data],['实验室与数据类型',c=>c.laboratory+' · '+c.dataSubtype],['AI 方法类别',c=>c.methodFamily],['问题类型',c=>c.problemType],['AI 方法',c=>c.aiMethod],['研究步骤',c=>c.pipeline.map(x=>x.title).join(' → ')],['评价指标',c=>c.metrics||'见原卡正文'],['论文结果',c=>c.result],['验证与边界',c=>[c.validation,c.boundary].filter(Boolean).join('；')||'见原卡正文']];$('#compare-table').innerHTML='<table><thead><tr><th scope="col">对照维度</th>'+cards.map(c=>`<th scope="col"><span class="compare-major" style="color:${c.color}">${esc(c.major)} · ${c.year}</span>${esc(c.short)}</th>`).join('')+'</tr></thead><tbody>'+fields.map(([label,get])=>'<tr><th scope="row">'+label+'</th>'+cards.map(c=>'<td>'+esc(get(c))+'</td>').join('')+'</tr>').join('')+'<tr><th scope="row">论文来源</th>'+cards.map(c=>'<td>'+esc(c.venue)+'<br>'+link('https://doi.org/'+c.doi,c.doi)+'</td>').join('')+'</tr></tbody></table>';$('#compare-dialog').showModal()}
// 方法图谱采用“方法总览 → 单方法论文”的两层结构，避免节点过多时整体缩小。
function renderMap(arr){
  const reset=$('#map-reset'),description=$('#map-description'),caption=$('#map-caption');
  if(!state.methodFamily){
    const stats=METHOD_FAMILIES.map(method=>{const cards=arr.filter(c=>c.methodFamily===method);return{method,cards}}).filter(item=>item.cards.length).sort((a,b)=>b.cards.length-a.cards.length||cjk(a.method,b.method));
    $('#map-canvas').innerHTML='<div class="method-overview">'+stats.map(({method,cards},i)=>{const examples=cards.slice(0,2).map(c=>c.short).join('、');return`<button class="method-overview-card" data-filter-key="methodFamily" data-filter-value="${esc(method)}" style="--method-color:${GROUP_COLORS[i%GROUP_COLORS.length]}" aria-label="查看${esc(method)}的${cards.length}篇论文"><span class="method-overview-index">${String(i+1).padStart(2,'0')}</span><strong>${cards.length}</strong><b>${esc(method)}</b><small>${esc(examples)}</small><em>查看论文 →</em></button>`}).join('')+'</div>';
    $('#graph-count').textContent=arr.length+' 篇论文 · '+stats.length+' 个方法分类';
    description.textContent='先选择一种方法，再查看关联论文；数量较多时也能保持清晰。';
    caption.textContent='方法数量按当前筛选结果统计；代表论文只用于帮助识别分类。';
    reset.hidden=true;
    return;
  }
  const pageSize=10,totalPages=Math.max(1,Math.ceil(arr.length/pageSize));
  state.mapPage=Math.min(Math.max(0,state.mapPage),totalPages-1);
  const start=state.mapPage*pageSize,shown=arr.slice(start,start+pageSize),w=960,h=Math.max(430,shown.length*78+70),methodY=h/2,paperY=i=>shown.length===1?h/2:48+i*((h-96)/Math.max(1,shown.length-1));
  let edges='',papers='';
  for(const [i,c] of shown.entries()){
    const y=paperY(i);
    edges+=`<path class="map-edge" data-edge-method="focus" data-edge-paper="${c.id}" d="M300 ${methodY} C330 ${methodY},330 ${y},370 ${y}"/>`;
    papers+=`<g class="graph-node graph-paper" role="button" tabindex="0" data-open-slug="${c.slug}" data-node-paper="${c.id}" aria-label="阅读${esc(c.title)}"><title>${esc(c.title)}</title><rect x="370" y="${y-31}" width="550" height="62" rx="8" fill="#fff" stroke="#d8e1e6"/><circle cx="370" cy="${y}" r="5" fill="${c.color}"/><text class="graph-label" x="391" y="${y-9}" font-size="10" fill="${c.color}">${esc(c.major)}</text><text class="graph-label" x="897" y="${y-9}" text-anchor="end" font-size="10" fill="#94a2a9">${c.year}</text><text class="graph-label" x="391" y="${y+14}" font-size="14" fill="#36556b">${esc(c.short)}</text></g>`;
  }
  const method=state.methodFamily,methodLabel=method.length>18?method.slice(0,18)+'…':method;
  const methodNode=`<g class="graph-node graph-method" role="button" tabindex="0" data-filter-key="methodFamily" data-filter-value="${esc(method)}" data-node-method="focus" aria-label="返回方法总览"><title>${esc(method)}：共 ${arr.length} 篇论文</title><rect x="35" y="${methodY-38}" width="265" height="76" rx="10" fill="#00468b" stroke="#00468b"/><text class="graph-label" x="56" y="${methodY-5}" font-size="14" fill="#fff">${esc(methodLabel)}</text><text class="graph-label" x="56" y="${methodY+19}" font-size="11" fill="#c9dceb">${arr.length} 篇论文 · 点击返回总览</text></g>`;
  const pager=totalPages>1?`<div class="map-pagination"><button data-map-page="prev" ${state.mapPage===0?'disabled':''}>← 上一组</button><span>第 ${state.mapPage+1} / ${totalPages} 组 · 显示 ${start+1}–${start+shown.length} 篇</span><button data-map-page="next" ${state.mapPage===totalPages-1?'disabled':''}>下一组 →</button></div>`:'';
  $('#map-canvas').innerHTML=`<div class="map-focus-label"><span>当前方法</span><strong>${esc(method)}</strong></div><svg viewBox="0 0 ${w} ${h}" role="group" aria-label="${esc(method)}与论文卡片的关联图谱">${edges}${methodNode}${papers}</svg>${pager}`;
  $('#graph-count').textContent=arr.length+' 篇论文 · 当前聚焦 1 个方法';
  description.textContent='当前只显示一个方法及其论文；点击论文阅读，分组翻页保持节点清晰。';
  caption.textContent='连线表示论文属于当前方法分类，不代表论文间的引用关系。';
  reset.hidden=false;reset.textContent='返回方法总览';reset.title='保留其他筛选，只退出当前方法';
}
document.addEventListener('click',e=>{const mapPager=e.target.closest('[data-map-page]');if(mapPager){state.mapPage+=mapPager.dataset.mapPage==='next'?1:-1;render();return}const more=e.target.closest('#load-more');if(more){state.visible+=PAGE_SIZE;render();requestAnimationFrame(()=>more.isConnected&&more.focus());return}const save=e.target.closest('[data-save]');if(save){toggleSave(save.dataset.save);return}const compare=e.target.closest('[data-compare]');if(compare){toggleCompare(compare.dataset.compare);return}const filter=e.target.closest('[data-filter-key]');if(filter){const key=filter.dataset.filterKey,value=filter.dataset.filterValue||'';if(!['domainGroup','domain','methodFamily','problemType','laboratory','dataSubtype','year'].includes(key))return;const wasActive=state[key]===value;state[key]=wasActive?'':value;if(key==='domainGroup')state.domain='';if(key==='laboratory')state.dataSubtype='';if(key==='dataSubtype'&&!wasActive&&filter.dataset.lab)state.laboratory=filter.dataset.lab;state.visible=PAGE_SIZE;state.mapPage=0;render();return}const clear=e.target.closest('[data-clear]');if(clear){state[clear.dataset.clear]='';if(clear.dataset.clear==='domainGroup')state.domain='';if(clear.dataset.clear==='laboratory')state.dataSubtype='';state.visible=PAGE_SIZE;state.mapPage=0;render();return}const node=e.target.closest('[data-open-slug]');if(node){location.hash='paper/'+node.dataset.openSlug;return}const rt=e.target.closest('[data-reader-tab]');if(rt){state.readerTab=rt.dataset.readerTab;renderReaderTab();return}if(e.target.closest('#empty-action')){if(state.page==='saved'&&!state.saved.size){clearFilters();location.hash='explore'}else clearFilters()}});
$('#search').addEventListener('input',e=>{state.q=e.target.value;state.visible=PAGE_SIZE;state.mapPage=0;render()});$('#sort').addEventListener('change',e=>{state.sort=e.target.value;state.visible=PAGE_SIZE;state.mapPage=0;render()});$('#clear-filters').onclick=clearFilters;$('#map-reset').onclick=()=>{state.methodFamily='';state.mapPage=0;render()};$('#view-grid').onclick=()=>{state.layout='grid';render()};$('#view-list').onclick=()=>{state.layout='list';render()};$('#clear-compare').onclick=()=>{state.compare=[];render()};$('#open-compare').onclick=openCompare;$('#compare-close').onclick=()=>$('#compare-dialog').close();$('#reader-close').onclick=closeReader;$('#reader').addEventListener('cancel',e=>{e.preventDefault();closeReader()});$('#reader-save').onclick=()=>toggleSave(state.reader.id);$('#reader-compare').onclick=()=>toggleCompare(state.reader.id);$('#download-card').onclick=()=>download(state.reader.markdown,state.reader.short+'.md');$('#reader-image-button').onclick=()=>{const c=state.reader;$('#full-image').src=c.image;$('#full-image').alt=c.title+' · 原始论文卡片';$('#image-download').href=c.image;$('#image-download').download=c.short+'.png';$('#image-dialog').showModal()};$('#image-close').onclick=()=>$('#image-dialog').close();$('#filter-toggle').onclick=()=>{const open=$('.filters').classList.toggle('open');$('#filter-toggle').setAttribute('aria-expanded',String(open))};
$('#map-canvas').addEventListener('mouseover',e=>{const node=e.target.closest('.graph-node');if(!node)return;$$('.map-edge').forEach(edge=>edge.classList.toggle('highlight',node.dataset.nodeMethod!==undefined?edge.dataset.edgeMethod===node.dataset.nodeMethod:edge.dataset.edgePaper===node.dataset.nodePaper))});$('#map-canvas').addEventListener('mouseleave',()=>$$('.map-edge').forEach(edge=>edge.classList.remove('highlight')));$('#map-canvas').addEventListener('focusin',e=>{const node=e.target.closest('.graph-node');if(!node)return;$$('.map-edge').forEach(edge=>edge.classList.toggle('highlight',node.dataset.nodeMethod!==undefined?edge.dataset.edgeMethod===node.dataset.nodeMethod:edge.dataset.edgePaper===node.dataset.nodePaper))});$('#map-canvas').addEventListener('focusout',()=>$$('.map-edge').forEach(edge=>edge.classList.remove('highlight')));
document.addEventListener('keydown',e=>{if((e.key==='/'||(e.ctrlKey&&e.key.toLowerCase()==='k'))&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!document.querySelector('dialog[open]')){e.preventDefault();$('#search').focus();$('#collection').scrollIntoView({behavior:'smooth'})}if((e.key==='Enter'||e.key===' ')&&e.target.matches('g[role=button]')){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}))}if(e.target.matches('[data-reader-tab]')&&['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const tabs=['overview','full','notes'];let i=tabs.indexOf(state.readerTab);i=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;state.readerTab=tabs[i];renderReaderTab();$('#tab-'+tabs[i]).focus()}});
window.addEventListener('hashchange',route);fillIcons();$('#stat-papers').textContent=String(CARDS.length).padStart(2,'0');$('#stat-domains').textContent=String(DOMAIN_GROUPS.length).padStart(2,'0');render();route();window.__atlasReady=true;
